# Generated by Django 4.1.3 on 2022-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moviemodel',
            fields=[
                ('Mid', models.BigAutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=50)),
                ('mdesc', models.TextField()),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('mpic', models.ImageField(upload_to='media/img/')),
            ],
        ),
    ]
